"""Stage 8: write results/REPORT.md — a plain-language summary of what the tables currently show.

Reads whatever exists in results/tables (fits_primary, stats_*, sim_summary) and the QC records.
Safe to run at any point; sections that lack inputs say so instead of failing.

Usage: python scripts/08_report.py
"""

import json
import sys
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd
import pingouin as pg

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from brainmaxxing.cli import base_parser, setup  # noqa: E402
from brainmaxxing.data import processed_blocks  # noqa: E402

TERMS = {"meditator": "trait (meditator − control)", "condition[T.meditation]": "state (meditation − thinking)",
         "meditator:condition[T.meditation]": "interaction"}


def fmt_p(p):
    return "< .001" if p < 0.001 else f"= {p:.3f}"


def main():
    args = base_parser(__doc__).parse_args()
    cfg, subjects = setup(args, source="derivatives")
    tables = Path(cfg["dataset"]["tables"])
    roi = cfg["stats"]["primary_roi"]
    out = [f"# BrainMaxxing — results so far ({date.today().isoformat()})", "",
           "Generated by `scripts/08_report.py` from `results/tables/`. Preliminary until the full "
           "dataset is processed; nothing here is confirmatory unless the sample line says n ≥ 94.", ""]

    # ---------------- sample and QC ----------------
    fits = pd.read_csv(tables / "fits_primary.csv")
    fits = fits[~fits.group.isin(cfg["stats"].get("exclude_groups", []))]
    d = fits[(fits.roi == roi) & (fits.fit_ok == True)]  # noqa: E712
    rejected, failed = [], []
    for sub in subjects:
        for task in processed_blocks(cfg, sub):
            qc = json.loads((Path(cfg["dataset"]["derivatives"]) / sub / f"{sub}_task-{task}_qc.json").read_text())
            if "failed" in qc:
                failed.append(f"{sub} {task}: {qc['failed'][:60]}")
            elif qc.get("n_epochs_kept", 0) < cfg["preprocess"]["epochs"].get("min_epochs", 30):
                rejected.append(f"{sub} {task}: {qc.get('n_epochs_kept', 0)} epochs")
    both = d.groupby("subject").condition.nunique()
    n_both = int((both == 2).sum())
    out += ["## Sample", "",
            f"- Subjects processed: **{fits.subject.nunique()}** "
            f"({d[d.meditator].subject.nunique()} meditators, {d[~d.meditator].subject.nunique()} controls); "
            f"by group: {d.groupby('tradition').subject.nunique().to_dict()}",
            f"- Usable blocks in the {roi} ROI: **{len(d)}**; subjects with both conditions: {n_both}",
            f"- Blocks rejected at preprocessing: {len(failed)}" + (f" ({'; '.join(failed[:6])}{'…' if len(failed) > 6 else ''})" if failed else ""),
            f"- Blocks with too few clean epochs: {len(rejected)}" + (f" ({'; '.join(rejected[:6])})" if rejected else ""),
            f"- Median epochs kept per block: {int(d.n_epochs_kept.median())} of ~300; "
            f"median ICLabel muscle variance: {d.ica_muscle_variance_ratio.median():.2f}", ""]

    # ---------------- fit quality ----------------
    r_ir = d[["exponent", "irasa_exponent"]].corr().iloc[0, 1] if "irasa_exponent" in d else np.nan
    out += ["## Fit quality", "",
            f"- specparam R² mean {d.r2.mean():.3f} (min {d.r2.min():.3f}); fits with R² < "
            f"{cfg['parameterize']['specparam']['min_r2']} excluded: "
            f"{int((fits[fits.roi == roi].fit_ok == False).sum())}",  # noqa: E712
            f"- Aperiodic exponent {d.exponent.mean():.2f} ± {d.exponent.std():.2f} (range {d.exponent.min():.2f}–{d.exponent.max():.2f})",
            f"- specparam vs IRASA exponent: r = {r_ir:.2f}, mean difference {(d.exponent - d.irasa_exponent).mean():+.2f}", ""]

    # ---------------- periodic gamma ----------------
    band = cfg["parameterize"]["gamma_band_hz"]
    prev = d.groupby("meditator").agg(blocks=("gamma_peak_present", "size"),
                                      counted=("gamma_peak_present", "sum"),
                                      pinned=("gamma_peak_pinned", "sum"))
    out += [f"## Is there a periodic {band[0]}–{band[1]} Hz peak?", "",
            f"Blocks with a countable peak: **{int(d.gamma_peak_present.sum())} of {len(d)}** "
            f"({100 * d.gamma_peak_present.mean():.0f} %); a further {int(d.gamma_peak_pinned.sum())} had a fitted "
            "peak whose bandwidth was pinned at a fitting limit (spectral line or range-edge curvature) and were not counted.", ""]
    for med, r in prev.iterrows():
        out.append(f"- {'Meditators' if med else 'Controls'}: {int(r.counted)} counted, {int(r.pinned)} pinned, of {int(r.blocks)} blocks")
    if d.gamma_peak_present.any():
        pk = d[d.gamma_peak_present]
        out.append(f"- Counted peaks: centre {pk.gamma_peak_cf.median():.0f} Hz (IQR {pk.gamma_peak_cf.quantile(.25):.0f}–{pk.gamma_peak_cf.quantile(.75):.0f}), "
                   f"power {pk.gamma_peak_pw.median():.2f} log10 units, bandwidth {pk.gamma_peak_bw.median():.0f} Hz")
    out += [f"- Mean periodic gamma power (flattened spectrum, {band[0]}–{band[1]} Hz): {d.periodic_gamma_power.mean():.3f} log10 units; "
            f"aperiodic component in the same band: {d.aperiodic_gamma_power.mean():.2f}", ""]

    # ---------------- state contrast within subjects ----------------
    out += ["## State contrast (meditation − thinking), paired within subject", ""]
    dvs = ["exponent", "irasa_exponent", "offset", "naive_gamma_power", "periodic_gamma_power",
           "emg_proxy_logpower", "ica_muscle_variance_ratio"]
    for label, sub_df in [("meditators", d[d.meditator]), ("controls", d[~d.meditator])]:
        sm = sub_df.groupby(["subject", "condition"])[dvs].mean().unstack("condition")
        if sm.shape[0] < 4 or ("meditation" not in sm.columns.levels[1]):
            out.append(f"- {label}: fewer than 4 subjects with both conditions — skipped")
            continue
        out += [f"**{label}** (n = {sm.shape[0]})", "", "| measure | mean diff | paired d | p |", "|---|---|---|---|"]
        for dv in dvs:
            a, b = sm[(dv, "thinking")], sm[(dv, "meditation")]
            ok = a.notna() & b.notna()
            if ok.sum() < 4:
                continue
            diff = (b[ok] - a[ok])
            t = pg.ttest(b[ok], a[ok], paired=True)
            pcol = "p_val" if "p_val" in t else "p-val"
            out.append(f"| {dv} | {diff.mean():+.3f} | {diff.mean() / diff.std(ddof=1):+.2f} | {fmt_p(float(t[pcol].iloc[0]))} |")
        out.append("")

    # ---------------- trait contrast, descriptive ----------------
    out += ["## Trait contrast (meditators vs controls), condition-averaged", ""]
    sm = d.groupby(["subject", "meditator"])[["exponent", "offset", "naive_gamma_power", "periodic_gamma_power",
                                              "emg_proxy_logpower"]].mean().reset_index()
    n_c, n_m = (~sm.meditator).sum(), sm.meditator.sum()
    if min(n_c, n_m) < 4:
        out.append(f"- Not estimable yet: {n_m} meditators vs {n_c} controls with usable data.")
    else:
        out += ["| measure | controls | meditators | d | p (Welch) |", "|---|---|---|---|---|"]
        for dv in ["exponent", "offset", "naive_gamma_power", "periodic_gamma_power", "emg_proxy_logpower"]:
            a, b = sm.loc[~sm.meditator, dv].dropna(), sm.loc[sm.meditator, dv].dropna()
            t = pg.ttest(b, a, paired=False)
            pcol = "p_val" if "p_val" in t else "p-val"
            out.append(f"| {dv} | {a.mean():.3f} | {b.mean():.3f} | {pg.compute_effsize(b, a):+.2f} | {fmt_p(float(t[pcol].iloc[0]))} |")
    out.append("")

    # ---------------- mixed model, TOST, EMG, dose ----------------
    mm = tables / "stats_mixed_2x2.csv"
    if mm.exists():
        m = pd.read_csv(mm)
        out += ["## Mixed model: measure ~ meditator × condition + order + (1 | subject)", "",
                "| measure | term | estimate [95 % CI] | p |", "|---|---|---|---|"]
        for dv in ["naive_gamma_power", "periodic_gamma_power", "offset", "exponent", "irasa_exponent"]:
            for term, name in TERMS.items():
                r = m[(m.dv == dv) & (m.term == term)]
                if len(r):
                    r = r.iloc[0]
                    out.append(f"| {dv} | {name} | {r.estimate:+.3f} [{r.ci_low:+.3f}, {r.ci_high:+.3f}] | {fmt_p(r.p)} |")
        out.append("")
        emg = tables / "stats_emg_confound.csv"
        if emg.exists():
            e = pd.read_csv(emg)
            out += ["### Trait effect before and after adjusting for scalp-muscle proxies", "",
                    "| measure | unadjusted | EMG-adjusted | attenuation |", "|---|---|---|---|"]
            for dv, g in e[e.term == "meditator"].groupby("dv"):
                u = g[g.model == "unadjusted"].estimate.iloc[0]
                a = g[g.model == "emg_adjusted"].estimate.iloc[0]
                out.append(f"| {dv} | {u:+.3f} | {a:+.3f} | {100 * (1 - a / u) if u else float('nan'):.0f} % |")
            out.append("")
        tost = tables / "stats_tost.csv"
        if tost.exists():
            t = pd.read_csv(tost)
            out += ["### Equivalence tests (TOST, bounds ± 0.5 pooled SD)", "",
                    "| measure | contrast | d | p(equivalence) |", "|---|---|---|---|"]
            for _, r in t.iterrows():
                out.append(f"| {r.dv} | {r.contrast} | {r.cohens_d:+.2f} | {fmt_p(r.p_tost)} |")
            out.append("")
        dose = tables / "stats_dose_response.csv"
        if dose.exists():
            ds = pd.read_csv(dose)
            out += ["### Dose–response with years of practice (meditators, Spearman)", "",
                    "| measure | n | rho | p |", "|---|---|---|---|"]
            for _, r in ds.iterrows():
                out.append(f"| {r.dv} | {int(r.n)} | {r.rho:+.2f} | {fmt_p(r.p)} |")
            out.append("")
    else:
        out += ["## Mixed model", "", "Not run yet (needs ≥ 4 subjects per group; run `05_stats.py`).", ""]

    # ---------------- simulation ----------------
    sim = tables / "sim_summary.csv"
    if sim.exists():
        s = pd.read_csv(sim).pivot(index="scenario", columns="measure", values="cohens_d")
        out += ["## Simulation (known ground truth, paired design)", "",
                "Cohen's d reported by each measure under each scenario:", "",
                "| scenario | naive band power | periodic power | exponent | offset |", "|---|---|---|---|---|"]
        for sc, r in s.iterrows():
            out.append(f"| {sc} | {r.naive_gamma_power:+.2f} | {r.periodic_gamma_power:+.2f} | {r.exponent:+.2f} | {r.offset:+.2f} |")
        out.append("")

    (Path(__file__).resolve().parents[1] / "results" / "REPORT.md").write_text("\n".join(out), encoding="utf-8")
    print("\n".join(out))


if __name__ == "__main__":
    main()
